# Generated by Django 4.1.2 on 2024-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
