# Generated by Django 4.1.4 on 2022-12-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('searching', '0002_learningobject_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='editedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
