# Generated by Django 4.1.2 on 2023-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0005_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselearningobject',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
