# Generated by Django 5.0.3 on 2024-03-30 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0006_courselearningobject_iscompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningobject',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='learningobject',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='learningobject',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobject',
            name='duration_min',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='keywords',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobject',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'english'), ('PORTUGUASE', 'portuguese')], default='portuguese'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningobject',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
