# Generated by Django 4.1.2 on 2024-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0007_alter_learningobject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningobject',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'english'), ('PORTUGUESE', 'portuguese')], max_length=10),
        ),
    ]
