# Generated by Django 4.1.2 on 2024-03-30 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0008_alter_learningobject_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningobject',
            old_name='duration_min',
            new_name='durationMin',
        ),
    ]
